force-app/main/default/objects/Patient_Record__c/Patient_Record__c.object-meta.xml
<CustomObject>
    <description>Store the records about patients visiting the hospital</description>
    <label>Patient Record</label>
    <nameField>
        <label>Patient Records Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Record__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Patient_Record__c/fields/Medical_Condition__c.field-meta.xml
<CustomField>
    <fullName>Medical_Condition__c</fullName>
    <description>A little description of the visit.</description>
    <label>Medical Condition</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Record__c/fields/Recorded_By__c.field-meta.xml
<CustomField>
    <fullName>Recorded_By__c</fullName>
    <description>Indicates the name of the medical practitioner who added the record</description>
    <label>Recorded By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NumberOfRecordedPatients.cls
public with sharing class NumberOfRecordedPatients {
    public NumberOfRecordedPatients() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Patient_Record__c> get() {
        return [SELECT Day__c, Medical_Condition__c, Name__c, Recorded_By__c 
        FROM Patient_Record__c
        WITH SECURITY_ENFORCED
        ORDER BY Day__c];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Patient_Record__c> getByCondition(String condition) {
        return [SELECT Day__c, Medical_Condition__c, Name__c, Recorded_By__c 
        FROM Patient_Record__c
        WHERE Medical_Condition__c=:condition
        WITH SECURITY_ENFORCED
        ORDER BY Day__c];
    }
    @AuraEnabled
    public static Patient_Record__c save(Patient_Record__c record){
        try {
            insert record;
            return record;
        } catch (Exception exp) {
            throw new AuraHandledException(exp.getMessage());
        }
    }
}