force-app/main/default/objects/Medical_Practitioner__c/Medical_Practitioner__c.object-meta.xml
<CustomObject>
    <label>Medical Practitioner</label>
    <nameField>
        <label>Medical Practitioner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Practitioners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Practitioner__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <inlineHelpText>e.g Doctor, nurse, pharmacist etc</inlineHelpText>
    <label>Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MedicRecords.cls
public with sharing class MedicRecords {
    public MedicRecords() {

    }
    @AuraEnabled(cacheable=true)
    public static List<Medical_Practitioner__c> get(){
        return [SELECT Name__c, Role__c 
        FROM Medical_Practitioner__c
        WITH SECURITY_ENFORCED
        ORDER BY Role__c
        ];
    }
    @AuraEnabled
    public static Medical_Practitioner__c save(Medical_Practitioner__c medical_practitioner){
        try {
            insert medical_practitioner;
            return medical_practitioner;
        } catch (Exception exp) {
            throw new AuraHandledException(exp.getMessage());
        }
    }
}